<a href="https://colab.research.google.com/github/arumm25/Repo1-PenambanganData/blob/main/Repository5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import roc_auc_score, roc_curve, mean_squared_error


In [3]:
path = '/content/drive/MyDrive/Penambangan Data/Social_Network_Ads.csv'
df = pd.read_csv(path)

df.head()


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df.info()
df.isnull().sum()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [5]:
df['Gender'] = df['Gender'].map({'Male':1, 'Female':0})


In [7]:
X = df[['Gender', 'Age', 'EstimatedSalary']]
y = df['Purchased']


In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


In [9]:
print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)


X_train shape: (320, 3)
X_test shape : (80, 3)
y_train shape: (320,)
y_test shape : (80,)


In [10]:
import numpy as np
print("Distribusi y_train:", np.unique(y_train, return_counts=True))
print("Distribusi y_test :", np.unique(y_test, return_counts=True))


Distribusi y_train: (array([0, 1]), array([206, 114]))
Distribusi y_test : (array([0, 1]), array([51, 29]))


In [11]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)


In [12]:
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)


GaussianNB()

In [13]:
y_pred = nb_model.predict(X_test)
y_prob = nb_model.predict_proba(X_test)[:,1]


In [14]:
y_pred[:10]


array([1, 0, 0, 1, 0, 1, 0, 1, 1, 0])

In [15]:
y_prob[:10]


array([0.96499546, 0.03049248, 0.11129788, 0.68020289, 0.01978568,
       0.87101022, 0.30951201, 0.99168506, 0.97561279, 0.10557342])

In [16]:
len(y_pred), len(y_test)

(80, 80)

In [17]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy Naive Bayes:", acc)

Accuracy Naive Bayes: 0.875


In [18]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.92      0.90        51
           1       0.85      0.79      0.82        29

    accuracy                           0.88        80
   macro avg       0.87      0.86      0.86        80
weighted avg       0.87      0.88      0.87        80



In [19]:
confusion_matrix(y_test, y_pred)

array([[47,  4],
       [ 6, 23]])

In [20]:
auc = roc_auc_score(y_test, y_prob)
print("AUC Naive Bayes:", auc)

AUC Naive Bayes: 0.949290060851927


In [21]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE Naive Bayes:", rmse)


RMSE Naive Bayes: 0.3535533905932738


In [22]:
import joblib

joblib.dump(nb_model, '/content/drive/MyDrive/model/naive_bayes_model.pkl')
joblib.dump(scaler, '/content/drive/MyDrive/model/scaler_nb.pkl')


['/content/drive/MyDrive/model/scaler_nb.pkl']